Perlmutter profiling
m2lines/Samudra pull request #10
Opened 2024-07-28 04:46 UTC by IamShubhamGupto

profiling using nsight

2024-07-28 23:13 UTC, suryadheeshjith commented on .python-perlmutter
* Need to change LOGDIR. 
* Why are we using two files i.e .python-perlmutter and .python-perlmutter-launch. Lets just use one.

2024-07-28 23:14 UTC, suryadheeshjith commented on configs/compute/greene/node/a100_1hrs.yaml
call it a100_45mins

2024-07-28 23:15 UTC, suryadheeshjith commented on configs/conf.yaml
Need to figure out separation of our conf files

2024-07-28 23:17 UTC, suryadheeshjith commented on scripts/train.sh
Create a new .sh file for profiling. Do not touch train and local_train.sh

2024-07-28 23:24 UTC, suryadheeshjith commented on src/train_3D.py
Can we modularize the code for profiling out of the train_3D.py file? If not, just create some functions for these lines of code. Also, it would be good if the profiling code runs only if a profiling flag is set in the configuration.

2024-07-28 23:38 UTC, suryadheeshjith commented on submitit_hydra.py
I want to test a few things with this code. What are the steps for me to run this code with profiling (other than path changes)? Would this work - ./.python-perlmutter submitit_hydra.py compute/greene=2x2 compute/greene/node=a100_3hrs wandb.mode=online exp=train_unet_global_3D_all epochs=4 name="$(date +%F)-train_convnextunet_global_3D_hist1_5levels" region=global_3D batch_size=4 scheduler=True rand_seed=10 unet.ch_width=[80,100,150,300,400] hist=1 --qos=preempt

Do I need to set the ENABLE_NSYS_PROFILING flag somewhere?

2024-07-28 23:39 UTC, suryadheeshjith requested changes
Ive added comments to the code

2024-07-29 02:39 UTC, IamShubhamGupto commented on configs/compute/greene/node/a100_1hrs.yaml
This file will be deleted, debug max is only 30mins

2024-07-29 02:42 UTC, IamShubhamGupto commented on .python-perlmutter
what changes you want in LOGDIR? want to send to m4331 project dir? 
`.python-perlmutter-launch` is used by submit_hydra to begin the experiment, I don't want profiling code to capture any of that

having a separate `.python-perlmutter` lets us launch nsys and cprofile directly on Trainer. Letting nsys observe submit_hydra launch Trainer does not seem to profile, same with cprofile. 

I can run another experiment on preempt to confirm this

2024-07-29 02:43 UTC, IamShubhamGupto commented on configs/conf.yaml
I can add it to gitignore, we use discord to observe changes in conf.yaml

2024-07-29 17:47 UTC, suryadheeshjith commented on configs/conf.yaml
I got a fix. I will push it

2024-07-29 17:54 UTC, suryadheeshjith commented on .python-perlmutter
No worries, lets keep both files and rename them. I want the all .sh fles to run .python-perlmutter so either we could exchange the file names or have something else like .python-perlmutter-worker or something.

2024-07-29 19:35 UTC, IamShubhamGupto commented on .python-perlmutter
with the latest commit, all .sh files can use either `.python-perlmutter-launch` or `.python-perlmutter`. For profiling, all .sh files must strictly use `.python-perlmutter-launch` for nsight to not break

we can rename it as long as `submitit_hydra.py` is calling the one with the Nsight modifications

2024-07-29 19:37 UTC, suryadheeshjith commented on .python-perlmutter
Yes, we will do that.

2024-07-30 15:04 UTC, IamShubhamGupto commented on .python-perlmutter-worker
> +    NSYS_ARGS="profile --trace=cuda,nvtx,osrt,cudnn,cublas --backtrace=dwarf --gpu-metrics-device=all"
Instead of `all`, set this to 0 for profiling on a single gpu

2024-07-30 15:19 UTC, suryadheeshjith commented on .python-perlmutter-worker
> +    NSYS_ARGS="profile --trace=cuda,nvtx,osrt,cudnn,cublas --backtrace=dwarf --gpu-metrics-device=all"
Will this disable profiling on all gpus instead? We want it to profile on all gpus but just prevent all of them to create an nsys file.

2024-08-20 20:14 UTC, closed without merging